pipeline {
    agent any
  tools {
    gradle 'gradle'
  }
  stages {
    stage('Prepare') {
      steps {
        checkout scm
        }
        post {
          success {
            echo "prepare stage success"
            echo pwd
          }
          failure {
            echo "prepare stage failed"
          }
        }
    }
    stage('Backend Build') {
      steps {
        dir('./backend') {
            echo "here is backend"
            sh 'docker stop backend || true && docker rm backend || true && docker rmi backend || true'
            sh 'gradle clean build -x test -b build.gradle' // .
            sh 'docker build -t backend .'
        }
      }
      post {
        always {
            echo "build stage complete"
        }
        failure {
            echo "build failed"
        }
        success {
            echo "build success"
        }
      }
    }
//     stage('Deploy') {
//       steps {
//         echo "deploy start"
//         // docker-compose.yml
//         sh 'cd /'
//         // docker-compose
//         sh 'docker-compose up -d'
//       }
//       post {
//         always {
//           echo "deploy stage complete"
//         }
//         failure {
//           echo "deploy failed"
//         }
//         success {
//           echo "deploy success"
//         }
//       }
//     }
  }
}